# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# includes/libraries
gems:
  - jekyll-app-engine

exclude: ['*.json', '*.enc', 'passets/']

title: Afnan Enayet
description: A personal website
permalink: /posts/:title/index.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "afnan-gapps.appspot.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: afnanenayet

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: aftapus

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: red

# Build settings
markdown: kramdown

# Settings for GAE
# Insert your configuration here or within _app.yaml
# You need to specify a runtime for App Engine
app_engine:
  runtime: go
  api_version: go1
  default_expiration: 300s

